# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(70, 180, 151, 28))
        self.btn_add.setObjectName("btn_add")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 457, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(50, 360, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_error_add = QtWidgets.QLabel(Form)
        self.label_error_add.setGeometry(QtCore.QRect(250, 170, 461, 31))
        self.label_error_add.setText("")
        self.label_error_add.setObjectName("label_error_add")
        self.tableWidgetEdit = QtWidgets.QTableWidget(Form)
        self.tableWidgetEdit.setGeometry(QtCore.QRect(160, 350, 601, 151))
        self.tableWidgetEdit.setObjectName("tableWidgetEdit")
        self.tableWidgetEdit.setColumnCount(0)
        self.tableWidgetEdit.setRowCount(0)
        self.tableWidgetAdd = QtWidgets.QTableWidget(Form)
        self.tableWidgetAdd.setGeometry(QtCore.QRect(10, 40, 781, 111))
        self.tableWidgetAdd.setObjectName("tableWidgetAdd")
        self.tableWidgetAdd.setColumnCount(0)
        self.tableWidgetAdd.setRowCount(0)
        self.label_error_edit = QtWidgets.QLabel(Form)
        self.label_error_edit.setGeometry(QtCore.QRect(200, 520, 461, 31))
        self.label_error_edit.setText("")
        self.label_error_edit.setObjectName("label_error_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add.setText(_translate("Form", "Добавить кофе"))
        self.pushButton_2.setText(_translate("Form", "Сохранить изменения"))
